const KEYS = {
    PROFILES: 'ap_profiles',
    ACTIVE_PROFILE: 'ap_active_profile',
    VISITORS: 'ap_visitor_count',
    // Dynamic keys generated by helpers
    PROFILE_PREFIX: 'ap_profile_',
    PREDICTIONS_PREFIX: 'ap_predictions_',
    HISTORY_PREFIX: 'ap_history_',
    COMPLETED_RECS_PREFIX: 'ap_completed_recs_'
};

export const storage = {
    KEYS,

    // --- Core Helpers ---
    get(key) {
        try {
            const item = localStorage.getItem(key);
            return item ? JSON.parse(item) : null;
        } catch (e) {
            console.error('Storage read error:', e);
            return null;
        }
    },

    set(key, value) {
        try {
            localStorage.setItem(key, JSON.stringify(value));
        } catch (e) {
            console.error('Storage write error:', e);
        }
    },

    // --- Profile Management ---
    getProfiles() {
        return this.get(KEYS.PROFILES) || [];
    },

    getActiveProfileId() {
        return this.get(KEYS.ACTIVE_PROFILE);
    },

    setActiveProfileId(id) {
        this.set(KEYS.ACTIVE_PROFILE, id);
    },

    createProfile(name) {
        const profiles = this.getProfiles();
        const newId = Date.now().toString(); // Simple ID generation
        const newProfile = { id: newId, name };
        
        profiles.push(newProfile);
        this.set(KEYS.PROFILES, profiles);
        this.setActiveProfileId(newId);
        
        return newId;
    },

    // Get current profile data (or specific ID)
    getProfile(id = null) {
        const targetId = id || this.getActiveProfileId();
        if (!targetId) return null;
        return this.get(`${KEYS.PROFILE_PREFIX}${targetId}`);
    },

    // Save profile data (Overwrites completely as requested)
    saveProfile(data, id = null) {
        const targetId = id || this.getActiveProfileId();
        if (!targetId) {
            // If no active profile exists, create a default one
            const newId = this.createProfile(data.firstName ? `${data.firstName} ${data.lastName}` : 'My Profile');
            this.set(`${KEYS.PROFILE_PREFIX}${newId}`, data);
            
            // Also clear old predictions for this new profile ID (though it's new, good practice)
            this.removePredictions(newId);
            return newId;
        }
        
        this.set(`${KEYS.PROFILE_PREFIX}${targetId}`, data);
        // Requirement 5: Clear old predictions when profile is saved
        this.removePredictions(targetId);
        return targetId;
    },

    // --- Predictions ---
    getPredictions(id = null) {
        const targetId = id || this.getActiveProfileId();
        if (!targetId) return null;
        return this.get(`${KEYS.PREDICTIONS_PREFIX}${targetId}`);
    },

    savePredictions(data, id = null) {
        const targetId = id || this.getActiveProfileId();
        if (!targetId) return;
        this.set(`${KEYS.PREDICTIONS_PREFIX}${targetId}`, data);
    },

    removePredictions(id) {
        localStorage.removeItem(`${KEYS.PREDICTIONS_PREFIX}${id}`);
    },

    // --- History ---
    addToHistory(score, id = null) {
        const targetId = id || this.getActiveProfileId();
        if (!targetId) return;
        
        const key = `${KEYS.HISTORY_PREFIX}${targetId}`;
        const history = this.get(key) || [];
        history.push({ timestamp: new Date().toISOString(), score });
        this.set(key, history);
    },

    getHistory(id = null) {
        const targetId = id || this.getActiveProfileId();
        if (!targetId) return [];
        return this.get(`${KEYS.HISTORY_PREFIX}${targetId}`) || [];
    },

    // --- Recommendations ---
    toggleRecCompletion(title, id = null) {
        const targetId = id || this.getActiveProfileId();
        if (!targetId) return;

        const key = `${KEYS.COMPLETED_RECS_PREFIX}${targetId}`;
        const completed = new Set(this.get(key) || []);
        
        if (completed.has(title)) {
            completed.delete(title);
        } else {
            completed.add(title);
        }
        this.set(key, Array.from(completed));
    },

    getCompletedRecs(id = null) {
        const targetId = id || this.getActiveProfileId();
        if (!targetId) return [];
        return this.get(`${KEYS.COMPLETED_RECS_PREFIX}${targetId}`) || [];
    },

    // --- Visitor Counter ---
    initVisitor() {
        // Requirement 1: "On every app load... increment by 1"
        // We use sessionStorage to ensure we only increment once per session load
        // but the value is stored in localStorage (ap_visitors)
        
        const isNewSession = !sessionStorage.getItem('ap_session_active');

        if (isNewSession) {
            sessionStorage.setItem('ap_session_active', 'true');
            
            let current = 12847; // Default base
            try {
                const stored = localStorage.getItem(KEYS.VISITORS);
                if (stored) {
                    current = parseInt(stored, 10);
                }
            } catch (e) {
                console.error("Visitor parse error", e);
            }

            const newValue = current + 1;
            localStorage.setItem(KEYS.VISITORS, newValue.toString());
            return newValue;
        }
        
        // Return current value without incrementing
        return this.getVisitorCount();
    },

    getVisitorCount() {
        try {
            const stored = localStorage.getItem(KEYS.VISITORS);
            return stored ? parseInt(stored, 10) : 12847;
        } catch (e) {
            return 12847;
        }
    }
};

// Expose to window for debugging
if (typeof window !== 'undefined') {
    window.storage = storage;
}
